### ISSUE TITLE
[BUG]: When more than one document is uploaded, bot returns the same response the same number of times as loaded documents 

### ISSUE THREAD

**Issue by dannygar** [microsoft/teams-copilot-starter#3]
**Describe the bug**
if you load two or more documents, the bot will give the same result the same number of loaded documents.

**To Reproduce**
1. Ask Bot to find some content in a website A
2. Ask Bot to find some content in a website B
3. Ask Bot the follow up question related to a website A

**Expected behavior**
The bot returns multiple times the same response

**Screenshots**
![image](https://github.com/microsoft/fsi-copilot/assets/1878251/192ef848-4c2d-4f34-9b01-d9558b2d05b7)

**Comment by svandenhoven** [comment]
this is caused by the code in chatwithDocuments.ts. This loops through all documents that are uploaded and generates an adaptive card for it. The same response is used for each document, even if it not the source

![image](https://github.com/microsoft/teams-copilot-starter/assets/13203032/bcb9db08-7f6d-4e1c-a3cf-23b7598de91e)

**Comment by svandenhoven** [comment]
see: https://github.com/microsoft/teams-copilot-starter/pull/13
